### ISSUE TITLE
Monitors including notifications are not idempotent

### ISSUE THREAD

**Issue by spkenney** [lucasheld/ansible-uptime-kuma#3]
If a monitor includes notifications, then that task always returns `changed` when re-run, even if the nothing in the monitor configuration has changed (i.e., these tasks are non-idempotent).

This issue is somewhat related to a previous [issue I filed on the uptime-kuma-api](https://github.com/lucasheld/uptime-kuma-api/issues/3) in that the need to translate the simple array of integer notification IDs into the dict of `{<id>: True, etc...}` looks to be the cause. I haven't looked into the Uptime Kuma source to try to understand why it needs that format, but maybe we can get that changed to avoid this translation entirely :)

Anyways, the issue is that the [object_changed function](https://github.com/lucasheld/ansible-uptime-kuma/blob/47005139f81d0c53a239b86c5770220ff9f8c8b6/plugins/module_utils/common.py#L8) in `module_utils/common.py` detects a "change" in notifications because it is comparing the object that looks like `{'14': True, '15': True}` returned from the existing monitor with the array of integers (`[14, 15]`) from the task's attributes, which obviously don't match, even though they represent the same notifications already being configured as the playbook is requested be configured.

I'll share my current workaround as a PR, but I am not sure it's the best way to solve this problem.

**Comment by lucasheld** [comment]
Thanks for the report and the PR.

Yes, in reflection it was not useful to change the structure of the Uptime Kuma API at some places. The reason for this conversion was just to optimize the data structure.

Currently, I will not remove this conversion to not cause a breaking change. Because it doesn't seem to be possible to accept an argument with two different types in the Ansible module for backward compatibility reasons.

Instead, I added the missing conversion to uptime-kuma-api so that ansible can compare the differences.
